/* mousewheelzoom.c generated by valac 0.40.7, the Vala compiler
 * generated from mousewheelzoom.vala, do not modify */

/* gnome-shell-mousewheel-zoom*/
/* (c) Mar 2012, Tobias Quinn <tobias@tobiasquinn.com>*/
/* GPLv3*/


#include <glib.h>
#include <glib-object.h>
#include <X11/Xlib.h>
#include <X11/Xatom.h>
#include <X11/Xutil.h>
#include <X11/Xregion.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <stdio.h>


#define TYPE_MAGNIFIER (magnifier_get_type ())
#define MAGNIFIER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAGNIFIER, Magnifier))
#define IS_MAGNIFIER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAGNIFIER))
#define MAGNIFIER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_MAGNIFIER, MagnifierIface))

typedef struct _Magnifier Magnifier;
typedef struct _MagnifierIface MagnifierIface;

#define TYPE_MAGNIFIER_PROXY (magnifier_proxy_get_type ())
typedef GDBusProxy MagnifierProxy;
typedef GDBusProxyClass MagnifierProxyClass;

#define TYPE_ZOOM_REGION (zoom_region_get_type ())
#define ZOOM_REGION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ZOOM_REGION, ZoomRegion))
#define IS_ZOOM_REGION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ZOOM_REGION))
#define ZOOM_REGION_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_ZOOM_REGION, ZoomRegionIface))

typedef struct _ZoomRegion ZoomRegion;
typedef struct _ZoomRegionIface ZoomRegionIface;

#define TYPE_ZOOM_REGION_PROXY (zoom_region_proxy_get_type ())
typedef GDBusProxy ZoomRegionProxy;
typedef GDBusProxyClass ZoomRegionProxyClass;

#define TYPE_ZOOMER (zoomer_get_type ())
#define ZOOMER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ZOOMER, Zoomer))
#define ZOOMER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ZOOMER, ZoomerClass))
#define IS_ZOOMER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ZOOMER))
#define IS_ZOOMER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ZOOMER))
#define ZOOMER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ZOOMER, ZoomerClass))

typedef struct _Zoomer Zoomer;
typedef struct _ZoomerClass ZoomerClass;
typedef struct _ZoomerPrivate ZoomerPrivate;
enum  {
	ZOOMER_0_PROPERTY,
	ZOOMER_NUM_PROPERTIES
};
static GParamSpec* zoomer_properties[ZOOMER_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define TYPE_WATCH_FOR_MAGNIFIER (watch_for_magnifier_get_type ())
#define WATCH_FOR_MAGNIFIER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_WATCH_FOR_MAGNIFIER, WatchForMagnifier))
#define WATCH_FOR_MAGNIFIER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_WATCH_FOR_MAGNIFIER, WatchForMagnifierClass))
#define IS_WATCH_FOR_MAGNIFIER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_WATCH_FOR_MAGNIFIER))
#define IS_WATCH_FOR_MAGNIFIER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_WATCH_FOR_MAGNIFIER))
#define WATCH_FOR_MAGNIFIER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_WATCH_FOR_MAGNIFIER, WatchForMagnifierClass))

typedef struct _WatchForMagnifier WatchForMagnifier;
typedef struct _WatchForMagnifierClass WatchForMagnifierClass;
typedef struct _WatchForMagnifierPrivate WatchForMagnifierPrivate;
enum  {
	WATCH_FOR_MAGNIFIER_0_PROPERTY,
	WATCH_FOR_MAGNIFIER_NUM_PROPERTIES
};
static GParamSpec* watch_for_magnifier_properties[WATCH_FOR_MAGNIFIER_NUM_PROPERTIES];
#define _g_main_loop_unref0(var) ((var == NULL) ? NULL : (var = (g_main_loop_unref (var), NULL)))
#define _XCloseDisplay0(var) ((var == NULL) ? NULL : (var = (XCloseDisplay (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _MagnifierIface {
	GTypeInterface parent_iface;
	gboolean (*isActive) (Magnifier* self, GError** error);
	void (*setActive) (Magnifier* self, gboolean active, GError** error);
	char** (*getZoomRegions) (Magnifier* self, int* result_length1, GError** error);
};

struct _ZoomRegionIface {
	GTypeInterface parent_iface;
	void (*setMagFactor) (ZoomRegion* self, gdouble xMagFactor, gdouble yMagFactor, GError** error);
	gdouble (*getMagFactor) (ZoomRegion* self, GError** error);
};

struct _Zoomer {
	GObject parent_instance;
	ZoomerPrivate * priv;
};

struct _ZoomerClass {
	GObjectClass parent_class;
};

struct _ZoomerPrivate {
	Magnifier* mag;
	ZoomRegion* zoom;
	gdouble current_zoom;
	gboolean zoom_active;
	gboolean interfaces_active;
};

struct _WatchForMagnifier {
	GObject parent_instance;
	WatchForMagnifierPrivate * priv;
};

struct _WatchForMagnifierClass {
	GObjectClass parent_class;
};

struct _WatchForMagnifierPrivate {
	GMainLoop* loop;
};


static gpointer zoomer_parent_class = NULL;
static gpointer watch_for_magnifier_parent_class = NULL;

#define MOUSEWHEEL_UP 4
#define MOUSEWHEEL_DOWN 5
GType magnifier_proxy_get_type (void) G_GNUC_CONST;
guint magnifier_register_object (void* object,
                                 GDBusConnection* connection,
                                 const gchar* path,
                                 GError** error);
GType magnifier_get_type (void) G_GNUC_CONST;
gboolean magnifier_isActive (Magnifier* self,
                             GError** error);
void magnifier_setActive (Magnifier* self,
                          gboolean active,
                          GError** error);
char** magnifier_getZoomRegions (Magnifier* self,
                                 int* result_length1,
                                 GError** error);
static void magnifier_proxy_g_signal (GDBusProxy* proxy,
                               const gchar* sender_name,
                               const gchar* signal_name,
                               GVariant* parameters);
static gboolean magnifier_proxy_isActive (Magnifier* self,
                                   GError** error);
static void magnifier_proxy_setActive (Magnifier* self,
                                gboolean active,
                                GError** error);
static char** magnifier_proxy_getZoomRegions (Magnifier* self,
                                       int* result_length1,
                                       GError** error);
static void magnifier_proxy_magnifier_interface_init (MagnifierIface* iface);
static void _dbus_magnifier_isActive (Magnifier* self,
                               GVariant* _parameters_,
                               GDBusMethodInvocation* invocation);
static void _dbus_magnifier_setActive (Magnifier* self,
                                GVariant* _parameters_,
                                GDBusMethodInvocation* invocation);
static void _dbus_magnifier_getZoomRegions (Magnifier* self,
                                     GVariant* _parameters_,
                                     GDBusMethodInvocation* invocation);
static void magnifier_dbus_interface_method_call (GDBusConnection* connection,
                                           const gchar* sender,
                                           const gchar* object_path,
                                           const gchar* interface_name,
                                           const gchar* method_name,
                                           GVariant* parameters,
                                           GDBusMethodInvocation* invocation,
                                           gpointer user_data);
static GVariant* magnifier_dbus_interface_get_property (GDBusConnection* connection,
                                                 const gchar* sender,
                                                 const gchar* object_path,
                                                 const gchar* interface_name,
                                                 const gchar* property_name,
                                                 GError** error,
                                                 gpointer user_data);
static gboolean magnifier_dbus_interface_set_property (GDBusConnection* connection,
                                                const gchar* sender,
                                                const gchar* object_path,
                                                const gchar* interface_name,
                                                const gchar* property_name,
                                                GVariant* value,
                                                GError** error,
                                                gpointer user_data);
static void _magnifier_unregister_object (gpointer user_data);
GType zoom_region_proxy_get_type (void) G_GNUC_CONST;
guint zoom_region_register_object (void* object,
                                   GDBusConnection* connection,
                                   const gchar* path,
                                   GError** error);
GType zoom_region_get_type (void) G_GNUC_CONST;
void zoom_region_setMagFactor (ZoomRegion* self,
                               gdouble xMagFactor,
                               gdouble yMagFactor,
                               GError** error);
gdouble zoom_region_getMagFactor (ZoomRegion* self,
                                  GError** error);
static void zoom_region_proxy_g_signal (GDBusProxy* proxy,
                                 const gchar* sender_name,
                                 const gchar* signal_name,
                                 GVariant* parameters);
static void zoom_region_proxy_setMagFactor (ZoomRegion* self,
                                     gdouble xMagFactor,
                                     gdouble yMagFactor,
                                     GError** error);
static gdouble zoom_region_proxy_getMagFactor (ZoomRegion* self,
                                        GError** error);
static void zoom_region_proxy_zoom_region_interface_init (ZoomRegionIface* iface);
static void _dbus_zoom_region_setMagFactor (ZoomRegion* self,
                                     GVariant* _parameters_,
                                     GDBusMethodInvocation* invocation);
static void _dbus_zoom_region_getMagFactor (ZoomRegion* self,
                                     GVariant* _parameters_,
                                     GDBusMethodInvocation* invocation);
static void zoom_region_dbus_interface_method_call (GDBusConnection* connection,
                                             const gchar* sender,
                                             const gchar* object_path,
                                             const gchar* interface_name,
                                             const gchar* method_name,
                                             GVariant* parameters,
                                             GDBusMethodInvocation* invocation,
                                             gpointer user_data);
static GVariant* zoom_region_dbus_interface_get_property (GDBusConnection* connection,
                                                   const gchar* sender,
                                                   const gchar* object_path,
                                                   const gchar* interface_name,
                                                   const gchar* property_name,
                                                   GError** error,
                                                   gpointer user_data);
static gboolean zoom_region_dbus_interface_set_property (GDBusConnection* connection,
                                                  const gchar* sender,
                                                  const gchar* object_path,
                                                  const gchar* interface_name,
                                                  const gchar* property_name,
                                                  GVariant* value,
                                                  GError** error,
                                                  gpointer user_data);
static void _zoom_region_unregister_object (gpointer user_data);
GType zoomer_get_type (void) G_GNUC_CONST;
#define ZOOMER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_ZOOMER, ZoomerPrivate))
#define ZOOMER_incr 0.1
Zoomer* zoomer_new (void);
Zoomer* zoomer_construct (GType object_type);
static void zoomer_refresh_dbus (Zoomer* self);
void zoomer_zoomIn (Zoomer* self);
void zoomer_zoomOut (Zoomer* self);
static void zoomer_finalize (GObject * obj);
GType watch_for_magnifier_get_type (void) G_GNUC_CONST;
#define WATCH_FOR_MAGNIFIER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_WATCH_FOR_MAGNIFIER, WatchForMagnifierPrivate))
WatchForMagnifier* watch_for_magnifier_new (void);
WatchForMagnifier* watch_for_magnifier_construct (GType object_type);
static void watch_for_magnifier_on_name_appeared (WatchForMagnifier* self);
static void _watch_for_magnifier_on_name_appeared_gbus_name_appeared_callback (GDBusConnection* connection,
                                                                        const gchar* name,
                                                                        const gchar* name_owner,
                                                                        gpointer self);
static void watch_for_magnifier_on_name_vanished (WatchForMagnifier* self);
static void _watch_for_magnifier_on_name_vanished_gbus_name_vanished_callback (GDBusConnection* connection,
                                                                        const gchar* name,
                                                                        gpointer self);
static void watch_for_magnifier_finalize (GObject * obj);
void _vala_main (gchar** arg,
                 int arg_length1);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);

const gint BUTTONS[2] = {MOUSEWHEEL_UP, MOUSEWHEEL_DOWN};
const gint MASKS[4] = {0, (gint) Mod2Mask, (gint) LockMask, (gint) (LockMask | Mod2Mask)};
static const GDBusArgInfo _magnifier_dbus_arg_info_isActive_result = {-1, "result", "b"};
static const GDBusArgInfo * const _magnifier_dbus_arg_info_isActive_in[] = {NULL};
static const GDBusArgInfo * const _magnifier_dbus_arg_info_isActive_out[] = {&_magnifier_dbus_arg_info_isActive_result, NULL};
static const GDBusMethodInfo _magnifier_dbus_method_info_isActive = {-1, "isActive", (GDBusArgInfo **) (&_magnifier_dbus_arg_info_isActive_in), (GDBusArgInfo **) (&_magnifier_dbus_arg_info_isActive_out)};
static const GDBusArgInfo _magnifier_dbus_arg_info_setActive_active = {-1, "active", "b"};
static const GDBusArgInfo * const _magnifier_dbus_arg_info_setActive_in[] = {&_magnifier_dbus_arg_info_setActive_active, NULL};
static const GDBusArgInfo * const _magnifier_dbus_arg_info_setActive_out[] = {NULL};
static const GDBusMethodInfo _magnifier_dbus_method_info_setActive = {-1, "setActive", (GDBusArgInfo **) (&_magnifier_dbus_arg_info_setActive_in), (GDBusArgInfo **) (&_magnifier_dbus_arg_info_setActive_out)};
static const GDBusArgInfo _magnifier_dbus_arg_info_getZoomRegions_result = {-1, "result", "ao"};
static const GDBusArgInfo * const _magnifier_dbus_arg_info_getZoomRegions_in[] = {NULL};
static const GDBusArgInfo * const _magnifier_dbus_arg_info_getZoomRegions_out[] = {&_magnifier_dbus_arg_info_getZoomRegions_result, NULL};
static const GDBusMethodInfo _magnifier_dbus_method_info_getZoomRegions = {-1, "getZoomRegions", (GDBusArgInfo **) (&_magnifier_dbus_arg_info_getZoomRegions_in), (GDBusArgInfo **) (&_magnifier_dbus_arg_info_getZoomRegions_out)};
static const GDBusMethodInfo * const _magnifier_dbus_method_info[] = {&_magnifier_dbus_method_info_isActive, &_magnifier_dbus_method_info_setActive, &_magnifier_dbus_method_info_getZoomRegions, NULL};
static const GDBusSignalInfo * const _magnifier_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _magnifier_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _magnifier_dbus_interface_info = {-1, "org.gnome.Magnifier", (GDBusMethodInfo **) (&_magnifier_dbus_method_info), (GDBusSignalInfo **) (&_magnifier_dbus_signal_info), (GDBusPropertyInfo **) (&_magnifier_dbus_property_info)};
static const GDBusInterfaceVTable _magnifier_dbus_interface_vtable = {magnifier_dbus_interface_method_call, magnifier_dbus_interface_get_property, magnifier_dbus_interface_set_property};
static const GDBusArgInfo _zoom_region_dbus_arg_info_setMagFactor_xMagFactor = {-1, "xMagFactor", "d"};
static const GDBusArgInfo _zoom_region_dbus_arg_info_setMagFactor_yMagFactor = {-1, "yMagFactor", "d"};
static const GDBusArgInfo * const _zoom_region_dbus_arg_info_setMagFactor_in[] = {&_zoom_region_dbus_arg_info_setMagFactor_xMagFactor, &_zoom_region_dbus_arg_info_setMagFactor_yMagFactor, NULL};
static const GDBusArgInfo * const _zoom_region_dbus_arg_info_setMagFactor_out[] = {NULL};
static const GDBusMethodInfo _zoom_region_dbus_method_info_setMagFactor = {-1, "setMagFactor", (GDBusArgInfo **) (&_zoom_region_dbus_arg_info_setMagFactor_in), (GDBusArgInfo **) (&_zoom_region_dbus_arg_info_setMagFactor_out)};
static const GDBusArgInfo _zoom_region_dbus_arg_info_getMagFactor_result = {-1, "result", "d"};
static const GDBusArgInfo * const _zoom_region_dbus_arg_info_getMagFactor_in[] = {NULL};
static const GDBusArgInfo * const _zoom_region_dbus_arg_info_getMagFactor_out[] = {&_zoom_region_dbus_arg_info_getMagFactor_result, NULL};
static const GDBusMethodInfo _zoom_region_dbus_method_info_getMagFactor = {-1, "getMagFactor", (GDBusArgInfo **) (&_zoom_region_dbus_arg_info_getMagFactor_in), (GDBusArgInfo **) (&_zoom_region_dbus_arg_info_getMagFactor_out)};
static const GDBusMethodInfo * const _zoom_region_dbus_method_info[] = {&_zoom_region_dbus_method_info_setMagFactor, &_zoom_region_dbus_method_info_getMagFactor, NULL};
static const GDBusSignalInfo * const _zoom_region_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _zoom_region_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _zoom_region_dbus_interface_info = {-1, "org.gnome.Magnifier.ZoomRegion", (GDBusMethodInfo **) (&_zoom_region_dbus_method_info), (GDBusSignalInfo **) (&_zoom_region_dbus_signal_info), (GDBusPropertyInfo **) (&_zoom_region_dbus_property_info)};
static const GDBusInterfaceVTable _zoom_region_dbus_interface_vtable = {zoom_region_dbus_interface_method_call, zoom_region_dbus_interface_get_property, zoom_region_dbus_interface_set_property};

gboolean
magnifier_isActive (Magnifier* self,
                    GError** error)
{
#line 17 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 17 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	return MAGNIFIER_GET_INTERFACE (self)->isActive (self, error);
#line 321 "mousewheelzoom.c"
}


void
magnifier_setActive (Magnifier* self,
                     gboolean active,
                     GError** error)
{
#line 18 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	g_return_if_fail (self != NULL);
#line 18 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	MAGNIFIER_GET_INTERFACE (self)->setActive (self, active, error);
#line 334 "mousewheelzoom.c"
}


char**
magnifier_getZoomRegions (Magnifier* self,
                          int* result_length1,
                          GError** error)
{
#line 19 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 19 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	return MAGNIFIER_GET_INTERFACE (self)->getZoomRegions (self, result_length1, error);
#line 347 "mousewheelzoom.c"
}


static void
magnifier_default_init (MagnifierIface * iface)
{
}


GType
magnifier_get_type (void)
{
	static volatile gsize magnifier_type_id__volatile = 0;
	if (g_once_init_enter (&magnifier_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MagnifierIface), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) magnifier_default_init, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType magnifier_type_id;
		magnifier_type_id = g_type_register_static (G_TYPE_INTERFACE, "Magnifier", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (magnifier_type_id, G_TYPE_OBJECT);
		g_type_set_qdata (magnifier_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) magnifier_proxy_get_type);
		g_type_set_qdata (magnifier_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "org.gnome.Magnifier");
		g_type_set_qdata (magnifier_type_id, g_quark_from_static_string ("vala-dbus-interface-info"), (void*) (&_magnifier_dbus_interface_info));
		g_type_set_qdata (magnifier_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) magnifier_register_object);
		g_once_init_leave (&magnifier_type_id__volatile, magnifier_type_id);
	}
	return magnifier_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (MagnifierProxy, magnifier_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (TYPE_MAGNIFIER, magnifier_proxy_magnifier_interface_init) )
static void
magnifier_proxy_class_init (MagnifierProxyClass* klass)
{
	G_DBUS_PROXY_CLASS (klass)->g_signal = magnifier_proxy_g_signal;
}


static void
magnifier_proxy_g_signal (GDBusProxy* proxy,
                          const gchar* sender_name,
                          const gchar* signal_name,
                          GVariant* parameters)
{
}


static void
magnifier_proxy_init (MagnifierProxy* self)
{
}


static gboolean
magnifier_proxy_isActive (Magnifier* self,
                          GError** error)
{
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gboolean _result = FALSE;
	GVariant* _tmp2_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.gnome.Magnifier", "isActive");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		gboolean _tmp0_ = FALSE;
		return _tmp0_;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		gboolean _tmp1_ = FALSE;
		g_object_unref (_reply_message);
		return _tmp1_;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp2_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_get_boolean (_tmp2_);
	g_variant_unref (_tmp2_);
	g_object_unref (_reply_message);
	return _result;
}


static void
magnifier_proxy_setActive (Magnifier* self,
                           gboolean active,
                           GError** error)
{
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.gnome.Magnifier", "setActive");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_boolean (active));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static char**
magnifier_proxy_getZoomRegions (Magnifier* self,
                                int* result_length1,
                                GError** error)
{
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	char** _result = NULL;
	int _result_length1;
	GVariant* _tmp3_;
	char** _tmp4_;
	int _tmp4__length;
	int _tmp4__size;
	int _tmp4__length1;
	GVariantIter _tmp5_;
	GVariant* _tmp6_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.gnome.Magnifier", "getZoomRegions");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return NULL;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return NULL;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_result_length1 = 0;
	_tmp3_ = g_variant_iter_next_value (&_reply_iter);
	_tmp4_ = g_new (char*, 5);
	_tmp4__length = 0;
	_tmp4__size = 4;
	_tmp4__length1 = 0;
	g_variant_iter_init (&_tmp5_, _tmp3_);
	for (; (_tmp6_ = g_variant_iter_next_value (&_tmp5_)) != NULL; _tmp4__length1++) {
		if (_tmp4__size == _tmp4__length) {
			_tmp4__size = 2 * _tmp4__size;
			_tmp4_ = g_renew (char*, _tmp4_, _tmp4__size + 1);
		}
		_tmp4_[_tmp4__length++] = g_variant_dup_string (_tmp6_, NULL);
		g_variant_unref (_tmp6_);
	}
	_result_length1 = _tmp4__length1;
	_tmp4_[_tmp4__length] = NULL;
	_result = _tmp4_;
	g_variant_unref (_tmp3_);
	*result_length1 = _result_length1;
	g_object_unref (_reply_message);
	return _result;
}


static void
magnifier_proxy_magnifier_interface_init (MagnifierIface* iface)
{
	iface->isActive = magnifier_proxy_isActive;
	iface->setActive = magnifier_proxy_setActive;
	iface->getZoomRegions = magnifier_proxy_getZoomRegions;
}


static void
_dbus_magnifier_isActive (Magnifier* self,
                          GVariant* _parameters_,
                          GDBusMethodInvocation* invocation)
{
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message = NULL;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gboolean result;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	result = magnifier_isActive (self, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_boolean (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void
_dbus_magnifier_setActive (Magnifier* self,
                           GVariant* _parameters_,
                           GDBusMethodInvocation* invocation)
{
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gboolean active = FALSE;
	GVariant* _tmp7_;
	GDBusMessage* _reply_message = NULL;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	_tmp7_ = g_variant_iter_next_value (&_arguments_iter);
	active = g_variant_get_boolean (_tmp7_);
	g_variant_unref (_tmp7_);
	magnifier_setActive (self, active, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void
_dbus_magnifier_getZoomRegions (Magnifier* self,
                                GVariant* _parameters_,
                                GDBusMethodInvocation* invocation)
{
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message = NULL;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	char** result;
	int result_length1 = 0;
	char** _tmp8_;
	GVariantBuilder _tmp9_;
	int _tmp10_;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	result = magnifier_getZoomRegions (self, &result_length1, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_tmp8_ = result;
	g_variant_builder_init (&_tmp9_, G_VARIANT_TYPE ("ao"));
	for (_tmp10_ = 0; _tmp10_ < result_length1; _tmp10_++) {
		g_variant_builder_add_value (&_tmp9_, g_variant_new_object_path (*_tmp8_));
		_tmp8_++;
	}
	g_variant_builder_add_value (&_reply_builder, g_variant_builder_end (&_tmp9_));
	result = (_vala_array_free (result, result_length1, (GDestroyNotify) g_free), NULL);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void
magnifier_dbus_interface_method_call (GDBusConnection* connection,
                                      const gchar* sender,
                                      const gchar* object_path,
                                      const gchar* interface_name,
                                      const gchar* method_name,
                                      GVariant* parameters,
                                      GDBusMethodInvocation* invocation,
                                      gpointer user_data)
{
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "isActive") == 0) {
		_dbus_magnifier_isActive (object, parameters, invocation);
	} else if (strcmp (method_name, "setActive") == 0) {
		_dbus_magnifier_setActive (object, parameters, invocation);
	} else if (strcmp (method_name, "getZoomRegions") == 0) {
		_dbus_magnifier_getZoomRegions (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant*
magnifier_dbus_interface_get_property (GDBusConnection* connection,
                                       const gchar* sender,
                                       const gchar* object_path,
                                       const gchar* interface_name,
                                       const gchar* property_name,
                                       GError** error,
                                       gpointer user_data)
{
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean
magnifier_dbus_interface_set_property (GDBusConnection* connection,
                                       const gchar* sender,
                                       const gchar* object_path,
                                       const gchar* interface_name,
                                       const gchar* property_name,
                                       GVariant* value,
                                       GError** error,
                                       gpointer user_data)
{
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint
magnifier_register_object (gpointer object,
                           GDBusConnection* connection,
                           const gchar* path,
                           GError** error)
{
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_magnifier_dbus_interface_info), &_magnifier_dbus_interface_vtable, data, _magnifier_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void
_magnifier_unregister_object (gpointer user_data)
{
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


void
zoom_region_setMagFactor (ZoomRegion* self,
                          gdouble xMagFactor,
                          gdouble yMagFactor,
                          GError** error)
{
#line 24 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	g_return_if_fail (self != NULL);
#line 24 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	ZOOM_REGION_GET_INTERFACE (self)->setMagFactor (self, xMagFactor, yMagFactor, error);
#line 736 "mousewheelzoom.c"
}


gdouble
zoom_region_getMagFactor (ZoomRegion* self,
                          GError** error)
{
#line 25 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	g_return_val_if_fail (self != NULL, 0.0);
#line 25 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	return ZOOM_REGION_GET_INTERFACE (self)->getMagFactor (self, error);
#line 748 "mousewheelzoom.c"
}


static void
zoom_region_default_init (ZoomRegionIface * iface)
{
}


GType
zoom_region_get_type (void)
{
	static volatile gsize zoom_region_type_id__volatile = 0;
	if (g_once_init_enter (&zoom_region_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ZoomRegionIface), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) zoom_region_default_init, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType zoom_region_type_id;
		zoom_region_type_id = g_type_register_static (G_TYPE_INTERFACE, "ZoomRegion", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (zoom_region_type_id, G_TYPE_OBJECT);
		g_type_set_qdata (zoom_region_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) zoom_region_proxy_get_type);
		g_type_set_qdata (zoom_region_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "org.gnome.Magnifier.ZoomRegion");
		g_type_set_qdata (zoom_region_type_id, g_quark_from_static_string ("vala-dbus-interface-info"), (void*) (&_zoom_region_dbus_interface_info));
		g_type_set_qdata (zoom_region_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) zoom_region_register_object);
		g_once_init_leave (&zoom_region_type_id__volatile, zoom_region_type_id);
	}
	return zoom_region_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (ZoomRegionProxy, zoom_region_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (TYPE_ZOOM_REGION, zoom_region_proxy_zoom_region_interface_init) )
static void
zoom_region_proxy_class_init (ZoomRegionProxyClass* klass)
{
	G_DBUS_PROXY_CLASS (klass)->g_signal = zoom_region_proxy_g_signal;
}


static void
zoom_region_proxy_g_signal (GDBusProxy* proxy,
                            const gchar* sender_name,
                            const gchar* signal_name,
                            GVariant* parameters)
{
}


static void
zoom_region_proxy_init (ZoomRegionProxy* self)
{
}


static void
zoom_region_proxy_setMagFactor (ZoomRegion* self,
                                gdouble xMagFactor,
                                gdouble yMagFactor,
                                GError** error)
{
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.gnome.Magnifier.ZoomRegion", "setMagFactor");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_double (xMagFactor));
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_double (yMagFactor));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static gdouble
zoom_region_proxy_getMagFactor (ZoomRegion* self,
                                GError** error)
{
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gdouble _result = 0.0;
	GVariant* _tmp13_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.gnome.Magnifier.ZoomRegion", "getMagFactor");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		gdouble _tmp11_ = 0.0;
		return _tmp11_;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		gdouble _tmp12_ = 0.0;
		g_object_unref (_reply_message);
		return _tmp12_;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp13_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_get_double (_tmp13_);
	g_variant_unref (_tmp13_);
	g_object_unref (_reply_message);
	return _result;
}


static void
zoom_region_proxy_zoom_region_interface_init (ZoomRegionIface* iface)
{
	iface->setMagFactor = zoom_region_proxy_setMagFactor;
	iface->getMagFactor = zoom_region_proxy_getMagFactor;
}


static void
_dbus_zoom_region_setMagFactor (ZoomRegion* self,
                                GVariant* _parameters_,
                                GDBusMethodInvocation* invocation)
{
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gdouble xMagFactor = 0.0;
	GVariant* _tmp14_;
	gdouble yMagFactor = 0.0;
	GVariant* _tmp15_;
	GDBusMessage* _reply_message = NULL;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	_tmp14_ = g_variant_iter_next_value (&_arguments_iter);
	xMagFactor = g_variant_get_double (_tmp14_);
	g_variant_unref (_tmp14_);
	_tmp15_ = g_variant_iter_next_value (&_arguments_iter);
	yMagFactor = g_variant_get_double (_tmp15_);
	g_variant_unref (_tmp15_);
	zoom_region_setMagFactor (self, xMagFactor, yMagFactor, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void
_dbus_zoom_region_getMagFactor (ZoomRegion* self,
                                GVariant* _parameters_,
                                GDBusMethodInvocation* invocation)
{
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message = NULL;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gdouble result;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	result = zoom_region_getMagFactor (self, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_double (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void
zoom_region_dbus_interface_method_call (GDBusConnection* connection,
                                        const gchar* sender,
                                        const gchar* object_path,
                                        const gchar* interface_name,
                                        const gchar* method_name,
                                        GVariant* parameters,
                                        GDBusMethodInvocation* invocation,
                                        gpointer user_data)
{
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "setMagFactor") == 0) {
		_dbus_zoom_region_setMagFactor (object, parameters, invocation);
	} else if (strcmp (method_name, "getMagFactor") == 0) {
		_dbus_zoom_region_getMagFactor (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant*
zoom_region_dbus_interface_get_property (GDBusConnection* connection,
                                         const gchar* sender,
                                         const gchar* object_path,
                                         const gchar* interface_name,
                                         const gchar* property_name,
                                         GError** error,
                                         gpointer user_data)
{
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean
zoom_region_dbus_interface_set_property (GDBusConnection* connection,
                                         const gchar* sender,
                                         const gchar* object_path,
                                         const gchar* interface_name,
                                         const gchar* property_name,
                                         GVariant* value,
                                         GError** error,
                                         gpointer user_data)
{
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint
zoom_region_register_object (gpointer object,
                             GDBusConnection* connection,
                             const gchar* path,
                             GError** error)
{
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_zoom_region_dbus_interface_info), &_zoom_region_dbus_interface_vtable, data, _zoom_region_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void
_zoom_region_unregister_object (gpointer user_data)
{
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


Zoomer*
zoomer_construct (GType object_type)
{
	Zoomer * self = NULL;
	Magnifier* _tmp0_ = NULL;
	Magnifier* _tmp1_;
	Magnifier* _tmp2_;
	gboolean _tmp5_ = FALSE;
	Magnifier* _tmp6_;
	gboolean _tmp7_;
	GError * _inner_error_ = NULL;
#line 39 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	self = (Zoomer*) g_object_new (object_type, NULL);
#line 40 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	self->priv->interfaces_active = FALSE;
#line 41 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp1_ = g_initable_new (TYPE_MAGNIFIER_PROXY, NULL, &_inner_error_, "g-flags", 0, "g-name", "org.gnome.Magnifier", "g-bus-type", G_BUS_TYPE_SESSION, "g-object-path", "/org/gnome/Magnifier", "g-interface-name", "org.gnome.Magnifier", "g-interface-info", g_type_get_qdata (TYPE_MAGNIFIER, g_quark_from_static_string ("vala-dbus-interface-info")), NULL);
#line 41 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp0_ = (Magnifier*) _tmp1_;
#line 41 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 41 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 41 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		g_clear_error (&_inner_error_);
#line 41 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		return NULL;
#line 1058 "mousewheelzoom.c"
	}
#line 41 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp2_ = _tmp0_;
#line 41 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp0_ = NULL;
#line 41 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_g_object_unref0 (self->priv->mag);
#line 41 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	self->priv->mag = _tmp2_;
#line 1068 "mousewheelzoom.c"
	{
		gboolean _tmp3_ = FALSE;
#line 44 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp3_ = TRUE;
#line 44 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		while (TRUE) {
#line 44 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			if (!_tmp3_) {
#line 1077 "mousewheelzoom.c"
				gboolean _tmp4_;
#line 46 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				_tmp4_ = self->priv->interfaces_active;
#line 46 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				if (!(!_tmp4_)) {
#line 46 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
					break;
#line 1085 "mousewheelzoom.c"
				}
			}
#line 44 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			_tmp3_ = FALSE;
#line 45 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			zoomer_refresh_dbus (self);
#line 1092 "mousewheelzoom.c"
		}
	}
#line 48 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp6_ = self->priv->mag;
#line 48 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp5_ = magnifier_isActive (_tmp6_, &_inner_error_);
#line 48 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 48 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_g_object_unref0 (_tmp0_);
#line 48 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 48 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		g_clear_error (&_inner_error_);
#line 48 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		return NULL;
#line 1109 "mousewheelzoom.c"
	}
#line 48 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	self->priv->zoom_active = _tmp5_;
#line 49 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp7_ = self->priv->zoom_active;
#line 49 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	if (_tmp7_) {
#line 1117 "mousewheelzoom.c"
		gdouble _tmp8_ = 0.0;
		ZoomRegion* _tmp9_;
#line 50 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp9_ = self->priv->zoom;
#line 50 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp8_ = zoom_region_getMagFactor (_tmp9_, &_inner_error_);
#line 50 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 50 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			_g_object_unref0 (_tmp0_);
#line 50 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 50 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			g_clear_error (&_inner_error_);
#line 50 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			return NULL;
#line 1134 "mousewheelzoom.c"
		}
#line 50 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		self->priv->current_zoom = _tmp8_;
#line 1138 "mousewheelzoom.c"
	} else {
#line 52 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		self->priv->current_zoom = (gdouble) 1;
#line 1142 "mousewheelzoom.c"
	}
#line 39 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_g_object_unref0 (_tmp0_);
#line 39 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	return self;
#line 1148 "mousewheelzoom.c"
}


Zoomer*
zoomer_new (void)
{
#line 39 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	return zoomer_construct (TYPE_ZOOMER);
#line 1157 "mousewheelzoom.c"
}


static void
zoomer_refresh_dbus (Zoomer* self)
{
	GError * _inner_error_ = NULL;
#line 56 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	g_return_if_fail (self != NULL);
#line 1167 "mousewheelzoom.c"
	{
		Magnifier* _tmp0_;
		gint _tmp1_;
		char** _tmp2_;
		char** _tmp3_;
		gint _tmp3__length1;
		ZoomRegion* _tmp4_ = NULL;
		ZoomRegion* _tmp5_;
		ZoomRegion* _tmp6_;
#line 59 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp0_ = self->priv->mag;
#line 59 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp2_ = magnifier_getZoomRegions (_tmp0_, &_tmp1_, &_inner_error_);
#line 59 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp3_ = _tmp2_;
#line 59 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp3__length1 = _tmp1_;
#line 59 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp3_ = (_vala_array_free (_tmp3_, _tmp3__length1, (GDestroyNotify) g_free), NULL);
#line 59 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1189 "mousewheelzoom.c"
			goto __catch0_g_error;
		}
#line 60 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp5_ = g_initable_new (TYPE_ZOOM_REGION_PROXY, NULL, &_inner_error_, "g-flags", 0, "g-name", "org.gnome.Magnifier", "g-bus-type", G_BUS_TYPE_SESSION, "g-object-path", "/org/gnome/Magnifier/ZoomRegion/zoomer0", "g-interface-name", "org.gnome.Magnifier.ZoomRegion", "g-interface-info", g_type_get_qdata (TYPE_ZOOM_REGION, g_quark_from_static_string ("vala-dbus-interface-info")), NULL);
#line 60 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp4_ = (ZoomRegion*) _tmp5_;
#line 60 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1198 "mousewheelzoom.c"
			goto __catch0_g_error;
		}
#line 60 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp6_ = _tmp4_;
#line 60 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp4_ = NULL;
#line 60 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_g_object_unref0 (self->priv->zoom);
#line 60 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		self->priv->zoom = _tmp6_;
#line 63 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		self->priv->interfaces_active = TRUE;
#line 57 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_g_object_unref0 (_tmp4_);
#line 1213 "mousewheelzoom.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
#line 57 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		e = _inner_error_;
#line 57 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_inner_error_ = NULL;
#line 57 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_g_error_free0 (e);
#line 1225 "mousewheelzoom.c"
	}
	__finally0:
#line 57 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 57 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 57 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		g_clear_error (&_inner_error_);
#line 57 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		return;
#line 1236 "mousewheelzoom.c"
	}
}


void
zoomer_zoomIn (Zoomer* self)
{
	gboolean _tmp0_;
	GError * _inner_error_ = NULL;
#line 68 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	g_return_if_fail (self != NULL);
#line 69 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp0_ = self->priv->zoom_active;
#line 69 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	if (_tmp0_) {
#line 1252 "mousewheelzoom.c"
		gdouble _tmp1_;
#line 70 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp1_ = self->priv->current_zoom;
#line 70 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		self->priv->current_zoom = _tmp1_ * (1 + ZOOMER_incr);
#line 1258 "mousewheelzoom.c"
	} else {
		gdouble _tmp2_;
		Magnifier* _tmp3_;
#line 72 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp2_ = self->priv->current_zoom;
#line 72 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		self->priv->current_zoom = _tmp2_ * (1 + ZOOMER_incr);
#line 73 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp3_ = self->priv->mag;
#line 73 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		magnifier_setActive (_tmp3_, TRUE, &_inner_error_);
#line 73 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 73 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 73 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			g_clear_error (&_inner_error_);
#line 73 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			return;
#line 1278 "mousewheelzoom.c"
		}
#line 74 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		self->priv->zoom_active = TRUE;
#line 1282 "mousewheelzoom.c"
	}
	{
		ZoomRegion* _tmp4_;
		gdouble _tmp5_;
		gdouble _tmp6_;
#line 77 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp4_ = self->priv->zoom;
#line 77 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp5_ = self->priv->current_zoom;
#line 77 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp6_ = self->priv->current_zoom;
#line 77 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		zoom_region_setMagFactor (_tmp4_, _tmp5_, _tmp6_, &_inner_error_);
#line 77 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1298 "mousewheelzoom.c"
			goto __catch1_g_error;
		}
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError* e = NULL;
#line 76 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		e = _inner_error_;
#line 76 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_inner_error_ = NULL;
#line 79 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		zoomer_refresh_dbus (self);
#line 76 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_g_error_free0 (e);
#line 1314 "mousewheelzoom.c"
	}
	__finally1:
#line 76 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 76 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 76 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		g_clear_error (&_inner_error_);
#line 76 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		return;
#line 1325 "mousewheelzoom.c"
	}
}


void
zoomer_zoomOut (Zoomer* self)
{
	gboolean _tmp0_;
	GError * _inner_error_ = NULL;
#line 83 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	g_return_if_fail (self != NULL);
#line 84 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp0_ = self->priv->zoom_active;
#line 84 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	if (_tmp0_) {
#line 1341 "mousewheelzoom.c"
		gdouble _tmp1_;
		gdouble _tmp2_;
#line 85 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp1_ = self->priv->current_zoom;
#line 85 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		self->priv->current_zoom = _tmp1_ * (1.0 - ZOOMER_incr);
#line 86 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp2_ = self->priv->current_zoom;
#line 86 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		if (_tmp2_ <= ((gdouble) 1)) {
#line 1352 "mousewheelzoom.c"
			Magnifier* _tmp3_;
#line 87 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			self->priv->current_zoom = (gdouble) 1;
#line 88 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			_tmp3_ = self->priv->mag;
#line 88 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			magnifier_setActive (_tmp3_, FALSE, &_inner_error_);
#line 88 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 88 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 88 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				g_clear_error (&_inner_error_);
#line 88 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				return;
#line 1368 "mousewheelzoom.c"
			}
#line 89 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			self->priv->zoom_active = FALSE;
#line 1372 "mousewheelzoom.c"
		} else {
			{
				ZoomRegion* _tmp4_;
				gdouble _tmp5_;
				gdouble _tmp6_;
#line 92 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				_tmp4_ = self->priv->zoom;
#line 92 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				_tmp5_ = self->priv->current_zoom;
#line 92 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				_tmp6_ = self->priv->current_zoom;
#line 92 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				zoom_region_setMagFactor (_tmp4_, _tmp5_, _tmp6_, &_inner_error_);
#line 92 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1388 "mousewheelzoom.c"
					goto __catch2_g_error;
				}
			}
			goto __finally2;
			__catch2_g_error:
			{
				GError* e = NULL;
#line 91 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				e = _inner_error_;
#line 91 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				_inner_error_ = NULL;
#line 94 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				zoomer_refresh_dbus (self);
#line 91 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				_g_error_free0 (e);
#line 1404 "mousewheelzoom.c"
			}
			__finally2:
#line 91 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 91 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 91 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				g_clear_error (&_inner_error_);
#line 91 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				return;
#line 1415 "mousewheelzoom.c"
			}
		}
	}
}


static void
zoomer_class_init (ZoomerClass * klass)
{
#line 28 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	zoomer_parent_class = g_type_class_peek_parent (klass);
#line 28 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	g_type_class_add_private (klass, sizeof (ZoomerPrivate));
#line 28 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	G_OBJECT_CLASS (klass)->finalize = zoomer_finalize;
#line 1431 "mousewheelzoom.c"
}


static void
zoomer_instance_init (Zoomer * self)
{
#line 28 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	self->priv = ZOOMER_GET_PRIVATE (self);
#line 1440 "mousewheelzoom.c"
}


static void
zoomer_finalize (GObject * obj)
{
	Zoomer * self;
#line 28 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_ZOOMER, Zoomer);
#line 30 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_g_object_unref0 (self->priv->mag);
#line 31 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_g_object_unref0 (self->priv->zoom);
#line 28 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	G_OBJECT_CLASS (zoomer_parent_class)->finalize (obj);
#line 1456 "mousewheelzoom.c"
}


GType
zoomer_get_type (void)
{
	static volatile gsize zoomer_type_id__volatile = 0;
	if (g_once_init_enter (&zoomer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ZoomerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) zoomer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Zoomer), 0, (GInstanceInitFunc) zoomer_instance_init, NULL };
		GType zoomer_type_id;
		zoomer_type_id = g_type_register_static (G_TYPE_OBJECT, "Zoomer", &g_define_type_info, 0);
		g_once_init_leave (&zoomer_type_id__volatile, zoomer_type_id);
	}
	return zoomer_type_id__volatile;
}


static void
_watch_for_magnifier_on_name_appeared_gbus_name_appeared_callback (GDBusConnection* connection,
                                                                   const gchar* name,
                                                                   const gchar* name_owner,
                                                                   gpointer self)
{
#line 107 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	watch_for_magnifier_on_name_appeared ((WatchForMagnifier*) self);
#line 1482 "mousewheelzoom.c"
}


static void
_watch_for_magnifier_on_name_vanished_gbus_name_vanished_callback (GDBusConnection* connection,
                                                                   const gchar* name,
                                                                   gpointer self)
{
#line 107 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	watch_for_magnifier_on_name_vanished ((WatchForMagnifier*) self);
#line 1493 "mousewheelzoom.c"
}


WatchForMagnifier*
watch_for_magnifier_construct (GType object_type)
{
	WatchForMagnifier * self = NULL;
	GDBusConnection* conn = NULL;
	GDBusConnection* _tmp0_;
	GMainLoop* _tmp1_;
	GMainLoop* _tmp2_;
	GError * _inner_error_ = NULL;
#line 104 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	self = (WatchForMagnifier*) g_object_new (object_type, NULL);
#line 106 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp0_ = g_bus_get_sync (G_BUS_TYPE_SESSION, NULL, &_inner_error_);
#line 106 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	conn = _tmp0_;
#line 106 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 106 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 106 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		g_clear_error (&_inner_error_);
#line 106 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		return NULL;
#line 1520 "mousewheelzoom.c"
	}
#line 107 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	g_bus_watch_name_on_connection_with_closures (conn, "org.gnome.Magnifier", G_BUS_NAME_WATCHER_FLAGS_NONE, (GClosure*) ((_watch_for_magnifier_on_name_appeared_gbus_name_appeared_callback == NULL) ? NULL : g_cclosure_new ((GCallback) _watch_for_magnifier_on_name_appeared_gbus_name_appeared_callback, g_object_ref (self), (GClosureNotify) g_object_unref)), (GClosure*) ((_watch_for_magnifier_on_name_vanished_gbus_name_vanished_callback == NULL) ? NULL : g_cclosure_new ((GCallback) _watch_for_magnifier_on_name_vanished_gbus_name_vanished_callback, g_object_ref (self), (GClosureNotify) g_object_unref)));
#line 112 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp1_ = g_main_loop_new (NULL, FALSE);
#line 112 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_g_main_loop_unref0 (self->priv->loop);
#line 112 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	self->priv->loop = _tmp1_;
#line 113 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp2_ = self->priv->loop;
#line 113 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	g_main_loop_run (_tmp2_);
#line 104 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_g_object_unref0 (conn);
#line 104 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	return self;
#line 1538 "mousewheelzoom.c"
}


WatchForMagnifier*
watch_for_magnifier_new (void)
{
#line 104 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	return watch_for_magnifier_construct (TYPE_WATCH_FOR_MAGNIFIER);
#line 1547 "mousewheelzoom.c"
}


static void
watch_for_magnifier_on_name_appeared (WatchForMagnifier* self)
{
	GMainLoop* _tmp0_;
#line 116 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	g_return_if_fail (self != NULL);
#line 117 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	g_message ("mousewheelzoom.vala:117: name appeared\n");
#line 118 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp0_ = self->priv->loop;
#line 118 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	g_main_loop_quit (_tmp0_);
#line 1563 "mousewheelzoom.c"
}


static void
watch_for_magnifier_on_name_vanished (WatchForMagnifier* self)
{
#line 121 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	g_return_if_fail (self != NULL);
#line 122 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	g_message ("mousewheelzoom.vala:122: name vanished\n");
#line 1574 "mousewheelzoom.c"
}


static void
watch_for_magnifier_class_init (WatchForMagnifierClass * klass)
{
#line 101 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	watch_for_magnifier_parent_class = g_type_class_peek_parent (klass);
#line 101 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	g_type_class_add_private (klass, sizeof (WatchForMagnifierPrivate));
#line 101 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	G_OBJECT_CLASS (klass)->finalize = watch_for_magnifier_finalize;
#line 1587 "mousewheelzoom.c"
}


static void
watch_for_magnifier_instance_init (WatchForMagnifier * self)
{
#line 101 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	self->priv = WATCH_FOR_MAGNIFIER_GET_PRIVATE (self);
#line 1596 "mousewheelzoom.c"
}


static void
watch_for_magnifier_finalize (GObject * obj)
{
	WatchForMagnifier * self;
#line 101 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_WATCH_FOR_MAGNIFIER, WatchForMagnifier);
#line 102 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_g_main_loop_unref0 (self->priv->loop);
#line 101 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	G_OBJECT_CLASS (watch_for_magnifier_parent_class)->finalize (obj);
#line 1610 "mousewheelzoom.c"
}


GType
watch_for_magnifier_get_type (void)
{
	static volatile gsize watch_for_magnifier_type_id__volatile = 0;
	if (g_once_init_enter (&watch_for_magnifier_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WatchForMagnifierClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) watch_for_magnifier_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (WatchForMagnifier), 0, (GInstanceInitFunc) watch_for_magnifier_instance_init, NULL };
		GType watch_for_magnifier_type_id;
		watch_for_magnifier_type_id = g_type_register_static (G_TYPE_OBJECT, "WatchForMagnifier", &g_define_type_info, 0);
		g_once_init_leave (&watch_for_magnifier_type_id__volatile, watch_for_magnifier_type_id);
	}
	return watch_for_magnifier_type_id__volatile;
}


void
_vala_main (gchar** arg,
            int arg_length1)
{
	WatchForMagnifier* wfm = NULL;
	WatchForMagnifier* _tmp0_;
	GSettings* settings = NULL;
	GSettings* _tmp1_;
	gchar* key = NULL;
	GSettings* _tmp2_;
	gchar* _tmp3_;
	gboolean super_key = FALSE;
	GSettings* _tmp4_;
	gint keymask = 0;
	const gchar* _tmp5_;
	const gchar* _tmp6_;
	GQuark _tmp8_ = 0U;
#line 137 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	static GQuark _tmp7_label0 = 0;
#line 137 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	static GQuark _tmp7_label1 = 0;
#line 137 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	static GQuark _tmp7_label2 = 0;
#line 1651 "mousewheelzoom.c"
	gboolean _tmp9_;
	Display* disp = NULL;
	Display* _tmp11_;
	Window root = 0;
	Display* _tmp12_;
	XEvent evt = {0};
	Zoomer* zoom = NULL;
	Zoomer* _tmp18_;
#line 128 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp0_ = watch_for_magnifier_new ();
#line 128 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	wfm = _tmp0_;
#line 131 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp1_ = g_settings_new ("com.tobiasquinn.mousewheelzoom");
#line 131 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	settings = _tmp1_;
#line 132 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp2_ = settings;
#line 132 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp3_ = g_settings_get_string (_tmp2_, "modifier-key");
#line 132 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	key = _tmp3_;
#line 133 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp4_ = settings;
#line 133 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	super_key = g_settings_get_boolean (_tmp4_, "super-key");
#line 136 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	keymask = (gint) Mod1Mask;
#line 137 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp5_ = key;
#line 137 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp6_ = _tmp5_;
#line 137 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp8_ = (NULL == _tmp6_) ? 0 : g_quark_from_string (_tmp6_);
#line 137 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	if (_tmp8_ == ((0 != _tmp7_label0) ? _tmp7_label0 : (_tmp7_label0 = g_quark_from_static_string ("ctrl")))) {
#line 137 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		switch (0) {
#line 1690 "mousewheelzoom.c"
			default:
			{
#line 139 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				keymask = (gint) ControlMask;
#line 140 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				break;
#line 1697 "mousewheelzoom.c"
			}
		}
	} else if (_tmp8_ == ((0 != _tmp7_label1) ? _tmp7_label1 : (_tmp7_label1 = g_quark_from_static_string ("shift")))) {
#line 137 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		switch (0) {
#line 1703 "mousewheelzoom.c"
			default:
			{
#line 142 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				keymask = (gint) ShiftMask;
#line 143 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				break;
#line 1710 "mousewheelzoom.c"
			}
		}
	} else if (_tmp8_ == ((0 != _tmp7_label2) ? _tmp7_label2 : (_tmp7_label2 = g_quark_from_static_string ("super")))) {
#line 137 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		switch (0) {
#line 1716 "mousewheelzoom.c"
			default:
			{
#line 145 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				keymask = (gint) Mod4Mask;
#line 146 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				break;
#line 1723 "mousewheelzoom.c"
			}
		}
	}
#line 149 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp9_ = super_key;
#line 149 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	if (_tmp9_) {
#line 1731 "mousewheelzoom.c"
		gint _tmp10_;
#line 150 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp10_ = keymask;
#line 150 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		keymask = _tmp10_ | Mod4Mask;
#line 1737 "mousewheelzoom.c"
	}
#line 154 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp11_ = XOpenDisplay (NULL);
#line 154 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	disp = _tmp11_;
#line 155 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp12_ = disp;
#line 155 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	root = DefaultRootWindow (_tmp12_);
#line 1747 "mousewheelzoom.c"
	{
		gint* button_collection = NULL;
		gint button_collection_length1 = 0;
		gint _button_collection_size_ = 0;
		gint button_it = 0;
#line 156 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		button_collection = BUTTONS;
#line 156 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		button_collection_length1 = G_N_ELEMENTS (BUTTONS);
#line 156 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		for (button_it = 0; button_it < G_N_ELEMENTS (BUTTONS); button_it = button_it + 1) {
#line 1759 "mousewheelzoom.c"
			gint button = 0;
#line 156 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			button = button_collection[button_it];
#line 1763 "mousewheelzoom.c"
			{
				{
					gint* mask_collection = NULL;
					gint mask_collection_length1 = 0;
					gint _mask_collection_size_ = 0;
					gint mask_it = 0;
#line 157 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
					mask_collection = MASKS;
#line 157 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
					mask_collection_length1 = G_N_ELEMENTS (MASKS);
#line 157 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
					for (mask_it = 0; mask_it < G_N_ELEMENTS (MASKS); mask_it = mask_it + 1) {
#line 1776 "mousewheelzoom.c"
						gint mask = 0;
#line 157 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
						mask = mask_collection[mask_it];
#line 1780 "mousewheelzoom.c"
						{
							Display* _tmp13_;
							gint _tmp14_;
							gint _tmp15_;
							gint _tmp16_;
							Window _tmp17_;
#line 158 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
							_tmp13_ = disp;
#line 158 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
							_tmp14_ = button;
#line 158 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
							_tmp15_ = keymask;
#line 158 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
							_tmp16_ = mask;
#line 158 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
							_tmp17_ = root;
#line 158 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
							XGrabButton (_tmp13_, (guint) _tmp14_, (guint) (_tmp15_ | _tmp16_), _tmp17_, FALSE, (guint) 0, (gint) GrabModeAsync, (gint) GrabModeAsync, (Window) 0, (guint) 0);
#line 1799 "mousewheelzoom.c"
						}
					}
				}
			}
		}
	}
#line 171 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	memset (&evt, 0, sizeof (XEvent));
#line 172 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_tmp18_ = zoomer_new ();
#line 172 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	zoom = _tmp18_;
#line 173 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	while (TRUE) {
#line 1814 "mousewheelzoom.c"
		Display* _tmp19_;
		XEvent _tmp20_;
		XButtonEvent _tmp21_;
		guint _tmp22_;
#line 174 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp19_ = disp;
#line 174 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		XNextEvent (_tmp19_, &evt);
#line 175 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp20_ = evt;
#line 175 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp21_ = _tmp20_.xbutton;
#line 175 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		_tmp22_ = _tmp21_.button;
#line 175 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
		switch (_tmp22_) {
#line 175 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			case MOUSEWHEEL_UP:
#line 1833 "mousewheelzoom.c"
			{
				Zoomer* _tmp23_;
#line 177 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				_tmp23_ = zoom;
#line 177 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				zoomer_zoomIn (_tmp23_);
#line 178 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				break;
#line 1842 "mousewheelzoom.c"
			}
#line 175 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
			case MOUSEWHEEL_DOWN:
#line 1846 "mousewheelzoom.c"
			{
				Zoomer* _tmp24_;
#line 181 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				_tmp24_ = zoom;
#line 181 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				zoomer_zoomOut (_tmp24_);
#line 182 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				break;
#line 1855 "mousewheelzoom.c"
			}
			default:
			{
				FILE* _tmp25_;
#line 185 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				_tmp25_ = stdout;
#line 185 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				fprintf (_tmp25_, "mousewheelzoom (vala) uncaught event\n");
#line 186 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
				break;
#line 1866 "mousewheelzoom.c"
			}
		}
	}
#line 126 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_g_object_unref0 (zoom);
#line 126 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_XCloseDisplay0 (disp);
#line 126 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_g_free0 (key);
#line 126 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_g_object_unref0 (settings);
#line 126 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_g_object_unref0 (wfm);
#line 1880 "mousewheelzoom.c"
}


int
main (int argc,
      char ** argv)
{
#line 126 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	_vala_main (argv, argc);
#line 126 "/home/pdostal/Documents/gnome-shell-mousewheel-zoom/mousewheelzoom.vala"
	return 0;
#line 1892 "mousewheelzoom.c"
}


static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



